### ISSUE TITLE
Accessibility in SVG export

### ISSUE THREAD

**Issue by eyssette** [gera2ld/markmap#110]
I've created mindmaps with markmap and received a comment that is more about Markmap.

https://github.com/eyssette/mindmap/issues/1

> 1. The SVG conveys meaning, but does not have a <title> element as first child. That one should give a short summary about the chart (think alt attribute for `<img />`. If you need more space, use an `<desc>` in addition.
> 2. The texts are `<div>` elements (wrapped in `<foreignObject>` to make SVG accept them. A `<text>` would be more apt here.
> 3. Your paths linking the nodes (= texts) are SVG `<path>` elements. That's fine. However, you loose the semantic of linking two nodes together.
>  
> Using Firefox Accessibility Inspector indicates to me, that it will start reading the text from the lower right end and move towards the left. With no indication on how the nodes are linked together. This will be somewhat tricky to get right.

Thank you for your wonderful software!

**Comment by gera2ld** [comment]
Thank you for the message.
But I think it is out of our scope. Point 1 is considerable, while point 2 and 3 are literally what this project relies on so it's unlikely to change.
