### ISSUE TITLE
uncaught TypeError: Cannot read properties of undefined (reading 'Markmap')

### ISSUE THREAD

**Issue by Sleep-bear** [gera2ld/markmap#115]
When my mind map grows to a certain extent, download the html, open it in the edge browser and display a blank, and the console displays an error. But the svg file is normal.
![image](https://user-images.githubusercontent.com/56720887/168722749-c0c2e6ab-4233-4ba8-bdcc-fe994c17f408.png)

Here is the approximate content of the interface
![image](https://user-images.githubusercontent.com/56720887/168723050-67b18944-c862-4348-ac4b-9fb23b6909e0.png)

**Comment by gera2ld** [comment]
> net::ERR_CONNECTION_RESET

It's a network problem, please check your network.
