### ISSUE TITLE
Cannot using multiline with block code

### ISSUE THREAD

**Issue by ngtrian** [gera2ld/markmap#116]
The displayed results will not match the example below
```
- code block
    ```js
    console.log('code block');
    ```
```

**Comment by gera2ld** [comment]
Not sure what you are talking about, please describe the expected and actual results.

**Comment by ngtrian** [comment]
![image](https://user-images.githubusercontent.com/4327817/174479761-488568e3-44ed-4651-8895-0451617132e2.png)

**Comment by gera2ld** [comment]
This is a known issue, only the first block of a list item will be shown. Perhaps related to #28
