### ISSUE TITLE
[Feature Request] Chemical Equations - KaTeX's `mhchem` extension

### ISSUE THREAD

**Issue by XiaoPanPanKevinPan** [gera2ld/markmap#120]
Hi! I was using this fantastic masterpiece. Since it supports KaTeX, I thought it was possible to write chemical equations with the `\ce` syntax, but it didn't work.

Could you please add this function? Thanks! 🙏🏻 

More about it in KaTeX's official repo: https://github.com/KaTeX/KaTeX/tree/main/contrib/mhchem

---
Below are some images

Error:
![image](https://user-images.githubusercontent.com/44266832/178986727-172b8bc2-7658-40be-aa1a-8de833238271.png)

Expectation:
![image](https://user-images.githubusercontent.com/44266832/178986885-32466089-d78e-48bb-96b9-1584304e748b.png)

**Comment by gera2ld** [comment]
In the latest version you can add your own plugins in frontmatter, see [demo](https://markmap.js.org/repl#?d=gist%3Agera2ld%2Faf76a4c245b302206b16aec503dbe07b%3Amhchem.md).

```md
---
markmap:
  extraJs:
    - https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/mhchem.min.js
---
```

**Comment by XiaoPanPanKevinPan** [comment]
> 

Thanks for your help!

**Comment by quarkape** [comment]
I use Vue, and extraJs doesn't words, and the I tried to create a script element, but it donen't work either.
if (styles) {
      await loadCSS(styles);
    }
    if (scripts) {
      await loadJS(scripts, {
        getMarkmap: () => markmap,
      });
    }
const script = document.createElement('script');
    script.type = 'text/javascript';
    script.src = 'https://cdn.jsdelivr.net/npm/katex@0.16.0/dist/contrib/mhchem.min.js';
    document.body.appendChild(script);
    const { root } = transformer.transform(this.markdownContent)
    this.markmapInstance = Markmap.create(this.$refs.svgRef, {autoFit: true, lineWidth: root => 4}, root)
    this.$nextTick(() => {
      setTimeout(() => {
          this.updateMindMap();
        }, 100);
      }
    );
