### ISSUE TITLE
[BUG] image display error

### ISSUE THREAD

**Issue by AidanDai** [gera2ld/markmap#170]
- [x] I have searched for existing issues that already reported this problem and found none
- [x] The bug is present in [REPL](https://markmap.js.org/repl)
  

**Expected behavior**

input in https://markmap.js.org/repl

```plain
# 1

## 1.1

### 1.1.1

- <img src="https://www.google.com.hk/images/branding/googlelogo/1x/googlelogo_color_272x92dp.png" alt="logo" height="100" width="100">

/`/`/`javascript 
console.log(123)
/`/`/`

# 2

## 2.1

### 2.1.1
```

output

![image](https://github.com/markmap/markmap/assets/11514661/c7dd2c30-edfa-476a-ba77-16572e2fcfd7)

**Actual behavior**

iamge display error when some input in https://markmap.js.org/repl

![image](https://github.com/markmap/markmap/assets/11514661/20b42862-238f-4277-a774-3f5a0d861473)

**Environment:**

- OS: macOS
- Browser: chrome
- Browser Version: 版本 112.0.5615.137（正式版本） (x86_64)

**Comment by simpleobj** [comment]
修复了吗，现在还是这样

**Comment by gera2ld** [comment]
Images are supported now.
