### ISSUE TITLE
Feature Request : Dark Mode

### ISSUE THREAD

**Issue by dctmfoo** [gera2ld/markmap#239]
Please add a toggle to switch to dark mode and back.

**Comment by dctmfoo** [comment]
Thank you. it works as expected!

**Comment by ika-musuko** [comment]
I can't find the dark mode toggle, attached is a screenshot of my markmap toolbar. 
<img width="230" alt="スクリーンショット 2024-07-05 14 22 58" src="https://github.com/markmap/markmap/assets/32429059/b4c1867a-530c-432e-b366-a67f9424fe4f">


I am using the latest commit on the master branch and installed markmap by running `npm install -g` directly in the git repository directory.

**Comment by gera2ld** [comment]
It is only implemented on the website, not in the library itself. It may be a good idea to also support it in the CLI, though.
