### ISSUE TITLE
Render Mindmap with closed nodes

### ISSUE THREAD

**Issue by pintergreg** [gera2ld/markmap#38]
My question / request is between #14 and #32, but I want to tell the renderer to collapse nodes from my JS code in client side, instead of Markdown or a separate UI button.

Actually, I solved this for myself, setting the _f_ property at every node before providing the data to the renderer (see the code below), but I think a global option would be nice at the transform or the render.

```html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <svg id="mindmap" width="700" height="500"></svg>
        <script src="https://cdn.jsdelivr.net/npm/d3@5"></script>
        <script src="https://cdn.jsdelivr.net/npm/markmap-lib@0.7.11/dist/browser/view.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/markmap-lib@0.7.11/dist/browser/transform.min.js"></script>

            <pre id="mm" hidden>
# foobar

## foo

- f
- o
- o

## bar

- b
- a
- r
        </pre>
        <script>
            function rec(data) {
                data.p = {f: true};
                for (var i in data.c) {
                    rec(data.c[i]);
                }
            }
            markdown =  document.getElementById("mm").innerHTML;
            const data = markmap.transform(markdown);

            rec(data);
            markmap.Markmap.create("#mindmap", null, data);
        </script>
    </body>
</html>
```

**Comment by lesaqiu** [comment]
3级深度以下节点折叠，我用的下面这个方法
`rec(data) {
      if (data.c && data.c.length > 0) {
        for (let i in data.c) {
          let dtemp = data.c[i];
          if (dtemp.d >= 3) {
            dtemp.p = _extends({}, dtemp.p, {
              f: true
            });
          } else {
            this.rec(dtemp);
          }
        }
      }
    }`


参考自源码中节点点击事件：
`handleClick(e, d) {
    var _data$p;

    const {
      data
    } = d;
    data.p = _extends({}, data.p, {
      f: !((_data$p = data.p) != null && _data$p.f)
    });
    this.renderData(d.data);
  }`

**Comment by lesaqiu** [comment]
3级深度以下节点折叠，我用的下面这个方法
```
rec(data) {
      if (data.c && data.c.length > 0) {
        for (let i in data.c) {
          let dtemp = data.c[i];
          if (dtemp.d >= 3) {
            dtemp.p = _extends({}, dtemp.p, {
              f: true
            });
          } else {
            this.rec(dtemp);
          }
        }
      }
    }
```

参考自源码中节点点击事件：
```
handleClick(e, d) {
var _data$p;
const {
  data
} = d;
data.p = _extends({}, data.p, {
  f: !((_data$p = data.p) != null && _data$p.f)
});
this.renderData(d.data);
}
```

**Comment by gera2ld** [comment]
Now you can add a comment next to a node to fold it, but not recursively. For example:

```md
- this node is expanded
  - a
  - b
  - c
- this node is folded <!-- fold -->
  - d
  - e
  - f
```

**Comment by gera2ld** [comment]
Now you can set `initialExpandLevel` in frontmatter:

```md
---
markmap:
  initialExpandLevel: 2
---
```

A new magic comment is added to fold a node and its children recursively:

```html
- this node is folded recursively <!-- fold recursively -->
  - 1
    - 1.1
  - 2
    - 2.1
  - 3
    - 3.1
```

Try it at <https://markmap.js.org/repl>

**Comment by sempervictus** [comment]
> Now you can set `initialExpandLevel` in frontmatter:
> 
> ```
> ---
> markmap:
>   initialExpandLevel: 2
> ---
> ```
> 
> A new magic comment is added to fold a node and its children recursively:
> 
> ```
> - this node is folded recursively 
>   - 1
>     - 1.1
>   - 2
>     - 2.1
>   - 3
>     - 3.1
> ```
> 
> Try it at https://markmap.js.org/repl

@gera2ld: how does one achieve this in the CLI? Seems to work great in the REPL, but not at all locally

**Comment by tamer73** [comment]
> Now you can set `initialExpandLevel` in frontmatter:
> 
> ```
> ---
> markmap:
>   initialExpandLevel: 2
> ---
> ```
> 
> A new magic comment is added to fold a node and its children recursively:
> 
> ```
> - this node is folded recursively 
>   - 1
>     - 1.1
>   - 2
>     - 2.1
>   - 3
>     - 3.1
> ```
> 
> Try it at https://markmap.js.org/repl

still not working with  <script src="https://cdn.jsdelivr.net/npm/markmap-autoloader@0.16"></script>

**Comment by outusuke** [comment]
> > Now you can set `initialExpandLevel` in frontmatter:
> > ```
> > ---
> > markmap:
> >   initialExpandLevel: 2
> > ---
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > A new magic comment is added to fold a node and its children recursively:
> > ```
> > - this node is folded recursively 
> >   - 1
> >     - 1.1
> >   - 2
> >     - 2.1
> >   - 3
> >     - 3.1
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Try it at https://markmap.js.org/repl
> 
> [@gera2ld](https://github.com/gera2ld): how does one achieve this in the CLI? Seems to work great in the REPL, but not at all locally

found the solution?

i'm using a a pos-processing script, like this

sed -i 's/initialExpandLevel: -1,/initialExpandLevel: 1,/' path_of_the_file
