### ISSUE TITLE
Repl on website not working anymore

### ISSUE THREAD

**Issue by pwab** [gera2ld/markmap#40]
I'm not sure since when this feature is broken but the repl on the website isn't working anymore (tested with current Firefox and Chrome). There is no sample that is shown up and no text can be typed into the box.

https://markmap.js.org/repl/

And by the way:
The link ["New feature: load markmap from Gist!"](https://markmap.js.org/undefined/#?file=gist.md) is giving me a 404.

**Comment by gera2ld** [comment]
It may be a network problem since the data is loaded from Gist now.
Can you confirm if you are able to open <https://api.github.com/gists/af76a4c245b302206b16aec503dbe07b>?



> The link ["New feature: load markmap from Gist!"](https://markmap.js.org/undefined/#?file=gist.md) is giving me a 404.

The link you pasted here is incorrect. [Here](https://markmap.js.org/repl/#?file=gist.md) is the correct link and works for me.

**Comment by pwab** [comment]
> Can you confirm if you are able to open https://api.github.com/gists/af76a4c245b302206b16aec503dbe07b?

This is what I see:

![grafik](https://user-images.githubusercontent.com/19271185/92236642-190d9300-eeb6-11ea-95d2-2428ed087a57.png)


> The link you pasted here is incorrect. Here is the correct link and works for me.

The link you provided works but I just copied the link from the website which leads to the 404:

![Unbenannt](https://user-images.githubusercontent.com/19271185/92236547-ec597b80-eeb5-11ea-9393-7ed987428876.png)

**Comment by gera2ld** [comment]
For some reason CodeMirror fails to load in your browser and leads to other problems. I've changed a bit and it should work now even without CodeMirror. Could you please confirm it?

**Comment by pwab** [comment]
Works now! 👍 

Just for debugging I'll provide some system info:
- Windows 10 2004 x64
- Firefox 81.0b6 (64-Bit)
- Chrome 85.0.4183.83 (Official Build) (64-Bit)

**Comment by gera2ld** [comment]
Closing as it works now
