### ISSUE TITLE
type for features in `ITransformResult`

### ISSUE THREAD

**Issue by DerMolly** [gera2ld/markmap#43]
Currently the type looks like this:
```
export interface ITransformResult {
    root: INode;
    features: any;
}
```
As `any` is a undesired type (or lack thereof) I'd like to change this.
Looking at the usage of features in 
https://github.com/gera2ld/markmap/blob/e944308c2272288ec5273098fb9de92001cab948/packages/markmap-lib/src/transform.ts#L175
the type of `features` seems to be `{ [key: string]: boolean; }`.

So a solution could be to just do the following:
```
export interface IFeatures { [key: string]: boolean; }
export interface ITransformResult {
    root: INode;
    features: IFeatures;
}
```
and using `IFeatures` in all other appropriate locations.

**Comment by DerMolly** [comment]
If you want I could open a PR for this.

**Comment by gera2ld** [comment]
Thanks for the suggestion, that could be better. I was concerned about other possibilities of the value in `features` but for now it's OK to be limited.
I'm glad to accept a PR, thanks.
