### ISSUE TITLE
Disable pan and zoom

### ISSUE THREAD

**Issue by DerMolly** [gera2ld/markmap#44]
Is it possible to deactivate the pan and zoom features?

**Comment by gera2ld** [comment]
There is no API or option for this but it seems to work by unregister the event listeners like this:

```js
mm.svg
  .on('wheel.zoom', null)
  .on('mousedown.zoom', null)
  .on('touchstart.zoom', null)
```

**Comment by DerMolly** [comment]
That's a gods suggestion. Thank you
