### ISSUE TITLE
“Download as interactive HTML“ doesn’t generate working HTML file

### ISSUE THREAD

**Issue by indysigner** [gera2ld/markmap#46]
Hi @gera2ld,

Love your Markmap-project since it started an few months back!

I noted that when downloading an interactive HTML file, it doesn’t output a working HTML any longer. There’s just an “undefined“ error shown in Firefox / Chrome and that’s it. Here’s my sample file... 

https://www.dropbox.com/s/ss9b4ykfs0f7925/201012-Information-Architecture.html?dl=0

Can you replicate the issue on your end?

**Comment by gera2ld** [comment]
It's caused by a wrong data structure, sorry for the trouble and thanks for the feedback. It should work now.
