### ISSUE TITLE
403 error code when access gist from github

### ISSUE THREAD

**Issue by colorlight** [gera2ld/markmap#48]
When I use the markmap to read gist from github, from the console of Chrome, I get a 403 error code, which said it is a rate limit error. It happens sometime, not always.

**Comment by gera2ld** [comment]
It seems like we have reached the rate limit of GitHub APIs, up to 60 requests per hour per unauthenticated user. Maybe we should add OAuth in the future.

Ref: https://docs.github.com/en/free-pro-team@latest/rest/overview/resources-in-the-rest-api#rate-limiting

**Comment by gera2ld** [comment]
@colorlight Now you can open the Gist with its raw URL in markmap, like `https://gist.github.com/gera2ld/af76a4c245b302206b16aec503dbe07b/raw/9c9c178a9d34af7776ad561dd38eaa2899e14fe5/markmap.md`.

**Comment by colorlight** [comment]
Thanks, but I failed to open the raw url in markmap with your demo url `https://gist.github.com/gera2ld/af76a4c245b302206b16aec503dbe07b/raw/9c9c178a9d34af7776ad561dd38eaa2899e14fe5/markmap.md`, there is a red 404 sign on the end of the `Open URL` line.

**Comment by gera2ld** [comment]
That must be a wrong URL 😿  , you can try with your own.

Closing since it works with the raw URL now.
