### ISSUE TITLE
Is it possible to use markmap directly in html

### ISSUE THREAD

**Issue by Blanket58** [gera2ld/markmap#53]
Just like mermaid, I can simplily use it in html by code like this.

```html
<head>
  <script src="https://cdn.bootcdn.net/ajax/libs/mermaid/8.8.2/mermaid.min.js"></script>
</head>

<div class="mermaid">
  graph TD
      Start --> Stop
</div>
```

**Comment by gera2ld** [comment]
Not now but I think it's a good idea.

**Comment by gera2ld** [comment]
It's supported now.
See [markmap-autoloader](https://github.com/gera2ld/markmap/tree/master/packages/markmap-autoloader).
