### ISSUE TITLE
Adopt npm

### ISSUE THREAD

**Issue by stefnotch** [gera2ld/markmap#54]
I'd love to contribute to this library (especially adding bidirectional mindmaps), however, it uses yarn.
Usually, this isn't an issue, since the user is free to either use yarn or npm. However here, with lerna, there are hardcoded calls to yarn.

On that note, I wonder if it would be worthwhile to check out the new [npm workspaces](https://github.com/npm/rfcs/blob/latest/implemented/0026-workspaces.md).

**Comment by gera2ld** [comment]
This project is based on yarn workspaces and does not work with `npm` command at the moment.
I'll see if I can fix it, but it may take some time.

What is the benefit to use npm workspaces over yarn workspaces, if we can't support them both?

**Comment by stefnotch** [comment]
Ideally, both npm and yarn would be perfectly supported. I think, but I'm not sure about this part, that yarn and npm workspaces should be compatible with each other.

If supporting them both is an issue, I would choose the one that the most important contributors, which would be you, prefer.

**Comment by gera2ld** [comment]
Just tweaked it and found it very simple to make it work with `npm` 😅

**Comment by stefnotch** [comment]
That was quick! Thank you very much

**Comment by gera2ld** [comment]
@stefnotch I'm afraid I'll have to switch back to yarn workspaces but I'll keep the commands with `npm run`.

This is what I get: yarn workspaces works out of the box and doesn't change my files, but npm messes up with my dependencies. Maybe npm workspaces works better but it does not work with lerna.

**Comment by stefnotch** [comment]
Ok, that's fine then.
