### ISSUE TITLE
Disable rendering code blocks

### ISSUE THREAD

**Issue by 0000sir** [gera2ld/markmap#59]
Markmap is a amazing tool for me, it changes every thing for document writers, we can write the document and print mind map at the same time. 

but there's a problem to do this, we use mermaid to draw sequence diagrams, and the Markmap will render them in the mind maps, that's not necessary for mind map viewers.

so is there a way to disable code block rending or provide a special mark to comment out some thing we want it in the document but don't want to show in mind maps? I've noticed some others want to disable table rendering #55

**Comment by ChristinWhite** [comment]
I was just hoping for the exact same thing, Markmap is fantastic but having huge code blocks in the map is really unwieldy.

**Comment by gera2ld** [comment]
Closing in favor of #71
