### ISSUE TITLE
Feature request: text color and hightlight

### ISSUE THREAD

**Issue by amberyli** [gera2ld/markmap#62]
Hi, this fab program is really really really useful! Thx!

Just wondering if it is possible to amend the colour or add a highlight of the text. The aim of this is to emphasize the thing. Thanks again!

**Comment by gera2ld** [comment]
It's already supported.
You can either create styled text with HTML or change CSS of the created markmap with APIs.

```js
import { Markmap } from 'markmap-view';

const mm = Markmap.create('#markmap', {
  style: id => `
    .${id}-fo > div { /* your css here */ }
  `,
}, data);
```
