### ISSUE TITLE
Fit graph in resized svg

### ISSUE THREAD

**Issue by neatc0der** [gera2ld/markmap#63]
Hi,

I've been working markmap for a couple of days now and I'm unable to find a good way to fit the graph into a resized sag without doing dirty code. Can you help me out?

My Idea:
* Load an arbitrary markdown content
* Use available width completely
* Adjust height according to the created mindmap (so no zoom is required)

The only thing I could come up with is this:
https://github.com/neatc0der/mkdocs-markmap/blob/4e419edb3b22351a6be0dff714b9265548b09517/mkdocs_markmap/templates/mkdocs-markmap.js#L12

Do you have any suggestions?

PS: Thanks for this awesome idea of create beautiful mindmaps in no time!

**Comment by gera2ld** [comment]
Did you try `mm.fit()` where `mm = Markmap.create(...)`?

**Comment by neatc0der** [comment]
Ok, so I've tried this:

```js
var el = document.querySelector('.mkdocs-markmap');
var content = el.getAttribute('data-markdown').replaceAll('&#10;', '\n');
var svg = el.querySelector('svg');

var root = markmap_transformer.transform(content).root;
var mm = markmap.Markmap.create(svg, null, root);

mm.rescale(1).then(function() {
    svg.parentElement.style.height = (svg.getBBox().height + 10) + "px";
    mm.fit();
});
```

Unfortunately, there is a `mm.state` containing x and y minima and maxima which determine the canvas. Changes to container size are not recognized by `mm.fit()`:

<img width="825" alt="markmap screenshot" src="https://user-images.githubusercontent.com/2805028/105962246-d83e3280-607f-11eb-9922-4c52de2bb0f3.png">

**Comment by gera2ld** [comment]
What about `setTimeout(() => { mm.fit(); })`?
`mm.fit` must be called after repaint so that it can get the new size.
You also need to make sure the SVG will always stretch to the container size.

**Comment by neatc0der** [comment]
Then, this happens:
<img width="825" alt="markmap screenshot 2" src="https://user-images.githubusercontent.com/2805028/105964118-1177a200-6082-11eb-9869-a559101f7374.png">

**Comment by gera2ld** [comment]
Can you provide a demo? Otherwise there is nothing much I can do.

**Comment by neatc0der** [comment]
Please find the example [here](https://github.com/gera2ld/markmap/files/5879753/test.zip). The corresponding javascript code starts at line 47.

**Comment by gera2ld** [comment]
It seems to be broken in Safari, which I guess is your case. I'll take a look at what is happening here.

**Comment by gera2ld** [comment]
The inline `svg` seems not properly rendered in Safari.
Simply adding `display: block` will help.

```diff
  .mkdocs-markmap > svg {
+   display: block;
  }
```

**Comment by neatc0der** [comment]
That did the trick, thanks!
