### ISSUE TITLE
Add "Fold All" and "Unfold All" button to markmap-toolbar.

### ISSUE THREAD

**Issue by DiscreteTom** [gera2ld/markmap#69]
It would be very useful when presenting with mindmap if we can **cascade** fold and unfold it.

**Comment by yoursamlan** [comment]
Yeah, especially when your markdown has  1000+ lines xD...

However, as of now, using the #38 technique, the following Python script can help to fold all the headings of a really long Markdown file

```
def foldAll(string_file):
    result = []
    for line in string_file.splitlines():
        if line.startswith('#') and not line.endswith("<!-- fold -->"):
            newline = line + " <!-- fold -->"
            line = newline
        result.append(line)
    return '\n'.join(result)

fname = input("Enter file path: ")   #eg -> Test.md

f = open(fname,"r",encoding="utf-8")
x = f.read()
y = foldAll(x)
f.close()
with open(fname,"w",encoding="utf-8") as f:
    f.write(y)
f.close()
```

**Comment by gera2ld** [comment]
Added in 64e82b7498b7f52d479d931b7a4b2f955dd0bd8d

Also added a new comment to fold a node and all its children initially (51f8ed9512078ad6bd49932bd46c7c5646dbc7d8):

```html
<!-- fold all -->
or
<!-- fold recursively -->
```
