### ISSUE TITLE
Hope to add a plug-in for Obsidian

### ISSUE THREAD

**Issue by AllenChengC8763** [gera2ld/markmap#73]
As title, [Obsidian](https://obsidian.md/) is a powerful knowledge base.
Hope to add a plug-in for Obsidian.

**Comment by AllenChengC8763** [comment]
I found that there is an alternative plug-in.
[lynchjames/obsidian-mind-map: An Obsidian plugin for displaying markdown notes as mind maps using Markmap.](https://github.com/lynchjames/obsidian-mind-map)

**Comment by gera2ld** [comment]
Closing since it seems to be resolved.
