### ISSUE TITLE
How to re-render a markdown?

### ISSUE THREAD

**Issue by luhggit** [gera2ld/markmap#85]
Markmap is great!

But it's docs is so simple...，so I have a question now:

I have created a svg mindmap-view using function "Mindmap.create('svg_id', null, root)", but if markdown content change, how can I re-render the view, and I found this function have accomplished in "Try it out" demo,  so How can I do it?

**Comment by gera2ld** [comment]
Sorry for the poor documentation.

You can keep the markmap instance and update it later. Here are some examples:

```js
const mm = Markmap.create(svg, null, root);

// update data
mm.setData(newRoot);

// fit the container
mm.fit();

// make sure node is visible in view port where node is root or one of its descendants
mm.ensureView(node);
```

Some real-world usage can be found in markmap-vscode: https://github.com/gera2ld/markmap-vscode/blob/master/assets/app.js
