### ISSUE TITLE
option to disable Prism in MarkMap autoloader

### ISSUE THREAD

**Issue by LisaFC** [gera2ld/markmap#91]
I really like MarkMap and one of our community members has added it as an option in [Docsy](https://github.com/google/docsy) using the [MarkMap autoloader](https://www.npmjs.com/package/markmap-autoloader). https://www.docsy.dev/docs/adding-content/diagrams-and-formulae/#mindmap-support-with-markmap

The only small issue we have is that we use Chroma as our default syntax highlighter, with the option to switch to Prism. However, because MarkMap loads the Prism files by default, if you have a MarkMap diagram and fenced code blocks in the same page, code blocks on that page *always* use Prism, regardless of what highlighter the user has chosen for the rest of their site. 
See: https://github.com/google/docsy/issues/729

Could there be any way to configure/toggle Prism highlighting in MarkMap for our Chroma users (or at least those Chroma users who have code blocks and MarkMap diagrams in the same page)?

**Comment by gera2ld** [comment]
Hi, thanks for the suggestion. This is possible in the latest `markmap-autoloader@0.2` now, see the demo [here](https://markmap.js.org/demos/auto-loader.html?disable=prism).
