### ISSUE TITLE
Limit max-width of nodes

### ISSUE THREAD

**Issue by keksundso** [gera2ld/markmap#92]
Currently, if I have a lot of text in a node I can sprinkle in some `<br />` to avoid unreadable mindmaps. However, this of course creates inconsistent results. 
Is it possible to define a width of the nodes, to automatically have line breaks.

**Comment by viktorbenei** [comment]
+1 on this, would make more complex mind maps way easier to work with

**Comment by rufuspollock** [comment]
Is this a duplicate of #76 ?

**Comment by keksundso** [comment]
The issue is a different one, but the reply is exactly what i looked for, thanks for the link. 

I am looking forward to the implementation of the feature.
